### ISSUE TITLE
数据库分库

### ISSUE THREAD

**Issue by MemeTao** [MemeTao/mcg#11]
数据库有两个表:
1. 学生课程表
2. 课程剩余人数表
（详细表结构字段见 database/v0.2.sql)

通过之前的测试我们发现，数据库的瓶颈在“更新”这两个表上，导致系统的选课性能卡在1000/S。现在希望通过“分库”的思想将系统的选课性能提高到3000/S。具体操作为：

按照二级学院分库，比如信息、量新、人文等每一个学院一个数据库，每个数据库都拥有上述的两张表，保存着自己学院的学生课程信息、自己学院发布的选修课剩余信息。当有某个选课请求到达，比如A学生选择B学院发布的一门选修课C，涉及的主要操作是：
1. 找到A学生的课程表所在的数据库，将C课程插入到A学生的课程表中。
2. 找到C课程所在的数据库，将剩余人数--

这个任务要负责的内容是：散列sql请求到相应的数据库上。
要求完成时间：6.10前。

**Comment by numbaa** [comment]
数据库分库更多的工作量实际在代码中，表设计是其次。
代码需要设计成可配置是否适用数据库分库、处理不同的分库逻辑。

**Comment by numbaa** [comment]
设计分库逻辑时，实际上要设计一个db proxy，把数据库接口都封装在此

**Comment by numbaa** [comment]
代码中的分库逻辑大致有了，但是在设计数据库表时，发现另一个问题。
必修课（此论选课前已有的课）和此次要选的课，它们的数据表应该独立开来，必修课的所有表都是静态的，选修课的课表(包含剩余人数)和关系表是可修改的，当所有选课工作完成后，只需同步这部分数据库到正方。
大致如下，其中粗体部分是课修改的：

-| - | - |- |-
------------ | ------------- | ------------- | ------------- | -------------
 \\ | 学生表(包含uid) |    |  | 全局唯一 
必修 | 课表(包含课id、剩余人数等) | 课程时间表  | 关系表 | 全局唯一
选修 | **课表**(包含课id、剩余人数等) | 课程时间表  | **关系表** | 每个学院单独存一个库

**Comment by numbaa** [comment]
done
